before:
  hooks:
    - make install
    - make gen
builds:
  -
    ldflags:
      - -s -w -X github.com/ohkrab/krab/krab.InfoVersion={{.Version}} -X github.com/ohkrab/krab/krab.InfoCommit={{.Commit}} -X github.com/ohkrab/krab/krab.InfoBuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0

    binary: krab

