builds:
  -
    ldflags:
      - -s -w -X github.com/ohkrab/krab/krab.InfoVersion={{.Version}} -X github.com/ohkrab/krab/krab.InfoCommit={{.Commit}} -X github.com/ohkrab/krab/krab.InfoBuildDate={{.Date}}
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    ignore:
      - goos: linux
        goarch: arm64

